---
title: "OLR"
author: '610811101'
date: "2020/10/6"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
# options(digits = 5)
library(magrittr)
library(ordinal) # clm
library(MASS) # polr
library(stats4)
setwd("G:/我的雲端硬碟/統計專論/作業一")
data <- read.csv("G:/我的雲端硬碟/統計專論/作業一/data_1.csv")
# summary(data$LTR.rating.categories)

# names(data)
categories_levels <- c("d","c","cc","ccc","b","bb","bbb","a","aa","aaa")
data$LTR.rating.categories <- factor(data$LTR.rating.categories,levels = categories_levels)

print("LTR.rating.categories的分布狀況")
summary(data$LTR.rating.categories)
data <- data[!(is.na(data) %>% rowSums()),] 
# is.na(data) %>% colSums()
# data$constant <- 1
print("去除了缺失值後，LTR.rating.categories的分布狀況")
summary(data$LTR.rating.categories)

print("25,50,75分位數  ")
qua <- quantile(as.numeric(data$LTR.rating.categories),1:3/4,na.rm = T)
categories_levels[qua] %>% `names<-`(names(qua))
```


```{r}
# clm(LTR.rating.categories~.-gvkey-Year,data = data,threshold = "flexible")

# clm(LTR.rating.categories~ constant + OM + TDL + DP + MBA + RDA + REA + CEA + CBA + TA + beta + sigma + size + IC + S.P.500.return,data = data,threshold = "flexible")

x <- polr(LTR.rating.categories~ IC + OM + TDL + DP + MBA + RDA + REA + CEA + CBA + TA + beta + sigma + size +  S.P.500.return,data = data,Hess = T)

# x$Hessian
summary(x)

y_hat <- predict(object = x,data)
table(y_hat,data$LTR.rating.categories)
# library(caret)
# confusionMatrix(table(y_hat,data$LTR.rating.categories))
```



```{r}
attach(data)
# 沒有截距項的
logistic <- function(x) 1/(1+exp(-x))

f_1 <- function(beta_1,beta_2,beta_3,beta_4,beta_5,beta_6,beta_7,beta_8,beta_9,beta_10,beta_11,beta_12,beta_13,beta_14,t_1,t_2,t_3,t_4,t_5,t_6,t_7,t_8,t_9){
  y_hat <- beta_1*IC+beta_2*OM+beta_3*TDL+beta_4*DP+beta_5*MBA+beta_6*RDA+beta_7*REA+beta_8*CEA+beta_9*CBA+beta_10*TA+beta_11*beta+beta_12*sigma+beta_13*size+beta_14*S.P.500.return
  t_2_x <- t_1+t_2
  t_3_x <- t_2_x+t_3
  t_4_x <- t_3_x+t_4
  t_5_x <- t_4_x+t_5
  t_6_x <- t_5_x+t_6
  t_7_x <- t_6_x+t_7
  t_8_x <- t_7_x+t_8
  t_9_x <- t_8_x+t_9
 # log_likelihood <- as.numeric(LTR.rating.categories=="d")*log(logistic(t_1-y_hat))+
 #    as.numeric(LTR.rating.categories=="c")*log(logistic(t_2_x-y_hat)-logistic(t_1-y_hat))+
 #   as.numeric(LTR.rating.categories=="cc")*log(logistic(t_3_x-y_hat)-logistic(t_2_x-y_hat))+
 #   as.numeric(LTR.rating.categories=="ccc")*log(logistic(t_4_x-y_hat)-logistic(t_3_x-y_hat))+
 #   as.numeric(LTR.rating.categories=="b")*log(logistic(t_5_x-y_hat)-logistic(t_4_x-y_hat))+
 #   as.numeric(LTR.rating.categories=="bb")*log(logistic(t_6_x-y_hat)-logistic(t_5_x-y_hat))+
 #   as.numeric(LTR.rating.categories=="bbb")*log(logistic(t_7_x-y_hat)-logistic(t_6_x-y_hat))+
 #   as.numeric(LTR.rating.categories=="a")*log(logistic(t_8_x-y_hat)-logistic(t_7_x-y_hat))+
 #   as.numeric(LTR.rating.categories=="aa")*log(logistic(t_9_x-y_hat)-logistic(t_8_x-y_hat))+
 #   as.numeric(LTR.rating.categories=="aaa")*log(1-logistic(t_9_x-y_hat))
 log_likelihood <- ifelse(LTR.rating.categories=="d",log(logistic(t_1-y_hat)),
                          ifelse(
                            LTR.rating.categories=="c",
                            log(logistic(t_2_x-y_hat)-logistic(t_1-y_hat)),
                            ifelse(
                            LTR.rating.categories=="cc",
                            log(logistic(t_3_x-y_hat)-logistic(t_2-y_hat)),
                            ifelse(
                            LTR.rating.categories=="ccc",
                            log(logistic(t_4_x-y_hat)-logistic(t_3-y_hat)),
                            ifelse(
                            LTR.rating.categories=="b",
                            log(logistic(t_5_x-y_hat)-logistic(t_4-y_hat)),
                            ifelse(
                            LTR.rating.categories=="bb",
                            log(logistic(t_6_x-y_hat)-logistic(t_5-y_hat)),
                            ifelse(
                            LTR.rating.categories=="bbb",
                            log(logistic(t_7_x-y_hat)-logistic(t_6-y_hat)),
                            ifelse(
                            LTR.rating.categories=="a",
                            log(logistic(t_8_x-y_hat)-logistic(t_7-y_hat)),
                            ifelse(
                            LTR.rating.categories=="aa",
                            log(logistic(t_9_x-y_hat)-logistic(t_8_x-y_hat)),
                            log(1-logistic(t_9_x-y_hat))
                          )
                          )
                          )
                          )
                          )
                          )
                          )
                          )
                          )

   -sum(log_likelihood)
}
start <- list(beta_1=1,beta_2=1,beta_3=1,beta_4=1,beta_5=1,beta_6=1,beta_7=1,beta_8=1,beta_9=1,beta_10=1,beta_11=1,beta_12=1,beta_13=1,beta_14=1,t_1=1,t_2=1,t_3=1,t_4=1,t_5=1,t_6=1,t_7=1,t_8=1,t_9=1)
# f_1_fit <- stats4::mle(f_1,start = start,nobs = nrow(data))
tryCatch(
    {
      f_1_fit <- stats4::mle(f_1,start = start,nobs = nrow(data), method = "L-BFGS-B",lower = c(rep(-Inf,(ncol(data)-2)),rep(0,length(start)-(ncol(data)-2))),upper = rep(Inf,length(start)))
    }
    ,warning = function(war)
        {
            
        }
        ,error = function(err)
        {
          
        }
  
  )

while(!exists("f_1_fit")){
  for(i in 1:length(start)){
    if(i <= (ncol(data)-3)){
      start[[i]] <- runif(1,min = -1,max = 1)
    }else{
      start[[i]] <- runif(1,min = 0,max = 1) 
    }
  }
  tryCatch(
    {
      f_1_fit <- stats4::mle(f_1,start = start,nobs = nrow(data), method = "L-BFGS-B",lower = c(rep(-Inf,(ncol(data)-2)),rep(0,length(start)-(ncol(data)-2))),upper = rep(Inf,length(start)))
    }
    ,warning = function(war)
        {
            
        }
        ,error = function(err)
        {
          
        }
  
  )
}
start_1 <- start
coeff_1 <- f_1_fit@coef

```

```{r}
predict_olr_1 <- function(coeff){
  y_hat <- coeff["beta_1"]*IC+coeff["beta_2"]*OM+coeff["beta_3"]*TDL+coeff["beta_4"]*DP+coeff["beta_5"]*MBA+coeff["beta_6"]*RDA+coeff["beta_7"]*REA+coeff["beta_8"]*CEA+coeff["beta_9"]*CBA+coeff["beta_10"]*TA+coeff["beta_11"]*beta+coeff["beta_12"]*sigma+coeff["beta_13"]*size+coeff["beta_14"]*S.P.500.return
  t_2_x <- coeff["t_1"]+coeff["t_2"]
  t_3_x <- t_2_x+coeff["t_3"]
  t_4_x <- t_3_x+coeff["t_4"]
  t_5_x <- t_4_x+coeff["t_5"]
  t_6_x <- t_5_x+coeff["t_6"]
  t_7_x <- t_6_x+coeff["t_7"]
  t_8_x <- t_7_x+coeff["t_8"]
  t_9_x <- t_8_x+coeff["t_9"]
  prob <- data.frame((logistic(coeff["t_1"]-y_hat)),
                       (logistic(t_2_x-y_hat)-logistic(coeff["t_1"]-y_hat)),(logistic(t_3_x-y_hat)-logistic(t_2_x-y_hat)),log(logistic(t_4_x-y_hat)-logistic(t_3_x-y_hat)),log(logistic(t_5_x-y_hat)-logistic(t_4_x-y_hat)),log(logistic(t_6_x-y_hat)-logistic(t_5_x-y_hat)),log(logistic(t_7_x-y_hat)-logistic(t_6_x-y_hat)),log(logistic(t_8_x-y_hat)-logistic(t_7_x-y_hat)),log(logistic(t_9_x-y_hat)-logistic(t_8_x-y_hat)),(1-logistic(t_9_x-y_hat)))
  apply(prob,1,which.max) %>% categories_levels[.] %>% factor(levels = categories_levels)
  # prob
}
y_hat_1 <- predict_olr_1(coeff_1)
confusionMatrix(table(y_hat_1,data$LTR.rating.categories))
```



```{r}
f_1_test <- function(beta_1,beta_2,beta_3,beta_4,beta_5,beta_6,beta_7,beta_8,beta_9,beta_10,beta_11,beta_12,beta_13,beta_14,t_1,t_2,t_3,t_4,t_5,t_6,t_7,t_8,t_9){
  y_hat <- beta_1*IC+beta_2*OM+beta_3*TDL+beta_4*DP+beta_5*MBA+beta_6*RDA+beta_7*REA+beta_8*CEA+beta_9*CBA+beta_10*TA+beta_11*beta+beta_12*sigma+beta_13*size+beta_14*S.P.500.return
  t_2_x <- t_1+t_2
  t_3_x <- t_2_x+t_3
  t_4_x <- t_3_x+t_4
  t_5_x <- t_4_x+t_5
  t_6_x <- t_5_x+t_6
  t_7_x <- t_6_x+t_7
  t_8_x <- t_7_x+t_8
  t_9_x <- t_8_x+t_9
likelihood <- (logistic(t_1-y_hat)^(LTR.rating.categories=="d"))*(logistic(t_2_x-y_hat)-logistic(t_1-y_hat))^(LTR.rating.categories=="c")*(logistic(t_3_x-y_hat)-logistic(t_2_x-y_hat))^(LTR.rating.categories=="cc")*(logistic(t_4_x-y_hat)-logistic(t_3_x-y_hat))^(LTR.rating.categories=="ccc")*(logistic(t_5_x-y_hat)-logistic(t_4_x-y_hat))^(LTR.rating.categories=="b")*(logistic(t_6_x-y_hat)-logistic(t_5_x-y_hat))^(LTR.rating.categories=="bb")*(logistic(t_7_x-y_hat)-logistic(t_6_x-y_hat))^(LTR.rating.categories=="bbb")*(logistic(t_8_x-y_hat)-logistic(t_7_x-y_hat))^(LTR.rating.categories=="a")*(logistic(t_9_x-y_hat)-logistic(t_8_x-y_hat))^(LTR.rating.categories=="aa")*(1-logistic(t_9_x-y_hat))^(LTR.rating.categories=="aaa")
-sum(likelihood)
}
start <- list(beta_1=1,beta_2=1,beta_3=1,beta_4=1,beta_5=1,beta_6=1,beta_7=1,beta_8=1,beta_9=1,beta_10=1,beta_11=1,beta_12=1,beta_13=1,beta_14=1,t_1=1,t_2=1,t_3=1,t_4=1,t_5=1,t_6=1,t_7=1,t_8=1,t_9=1)

while(!exists("f_1_test_fit")){
  for(i in 1:length(start)){
    if(i <= (ncol(data)-3)){
      start[[i]] <- runif(1,min = -1,max = 1)
    }else{
      start[[i]] <- runif(1,min = 0,max = 1) 
    }
  }
  tryCatch(
    {
      f_1_test_fit <- stats4::mle(f_1_test,start = start,nobs = nrow(data), method = "L-BFGS-B",lower = c(rep(-Inf,(ncol(data)-2)),rep(0,length(start)-(ncol(data)-2))),upper = rep(Inf,length(start)))
    }
    ,warning = function(war)
        {
            
        }
        ,error = function(err)
        {
          
        }
  
  )
}
start_1_test <- start
coeff_1_test <- f_1_test_fit@coef
```


```{r}
f_2 <- function(beta_1,beta_2,beta_3,beta_4,beta_5,beta_6,beta_7,beta_8,beta_9,beta_10,beta_11,beta_12,beta_13,beta_14,t_2,t_3,t_4,t_5,t_6,t_7,t_8,t_9,constant){
  y_hat <- constant+beta_1*IC+beta_2*OM+beta_3*TDL+beta_4*DP+beta_5*MBA+beta_6*RDA+beta_7*REA+beta_8*CEA+beta_9*CBA+beta_10*TA+beta_11*beta+beta_12*sigma+beta_13*size+beta_14*S.P.500.return
  t_2_x <- t_2
  t_3_x <- t_2_x+t_3
  t_4_x <- t_3_x+t_4
  t_5_x <- t_4_x+t_5
  t_6_x <- t_5_x+t_6
  t_7_x <- t_6_x+t_7
  t_8_x <- t_7_x+t_8
  t_9_x <- t_8_x+t_9
   # log_likelihood <- as.numeric(LTR.rating.categories=="d")*log(logistic(-y_hat))+
 #    as.numeric(LTR.rating.categories=="c")*log(logistic(t_2_x-y_hat)-logistic(-y_hat))+
 #   as.numeric(LTR.rating.categories=="cc")*log(logistic(t_3_x-y_hat)-logistic(t_2_x-y_hat))+
 #   as.numeric(LTR.rating.categories=="ccc")*log(logistic(t_4_x-y_hat)-logistic(t_3_x-y_hat))+
 #   as.numeric(LTR.rating.categories=="b")*log(logistic(t_5_x-y_hat)-logistic(t_4_x-y_hat))+
 #   as.numeric(LTR.rating.categories=="bb")*log(logistic(t_6_x-y_hat)-logistic(t_5_x-y_hat))+
 #   as.numeric(LTR.rating.categories=="bbb")*log(logistic(t_7_x-y_hat)-logistic(t_6_x-y_hat))+
 #   as.numeric(LTR.rating.categories=="a")*log(logistic(t_8_x-y_hat)-logistic(t_7_x-y_hat))+
 #   as.numeric(LTR.rating.categories=="aa")*log(logistic(t_9_x-y_hat)-logistic(t_8_x-y_hat))+
 #   as.numeric(LTR.rating.categories=="aaa")*log(1-logistic(t_9_x-y_hat))
  log_likelihood <- ifelse(LTR.rating.categories=="d",log(logistic(-y_hat)),
                           ifelse(
                             LTR.rating.categories=="c",
                             log(logistic(t_2_x-y_hat)-logistic(-y_hat)),
                             ifelse(
                             LTR.rating.categories=="cc",
                             log(logistic(t_3_x-y_hat)-logistic(t_2-y_hat)),
                             ifelse(
                             LTR.rating.categories=="ccc",
                             log(logistic(t_4_x-y_hat)-logistic(t_3-y_hat)),
                             ifelse(
                             LTR.rating.categories=="b",
                             log(logistic(t_5_x-y_hat)-logistic(t_4-y_hat)),
                             ifelse(
                             LTR.rating.categories=="bb",
                             log(logistic(t_6_x-y_hat)-logistic(t_5-y_hat)),
                             ifelse(
                             LTR.rating.categories=="bbb",
                             log(logistic(t_7_x-y_hat)-logistic(t_6-y_hat)),
                             ifelse(
                             LTR.rating.categories=="a",
                             log(logistic(t_8_x-y_hat)-logistic(t_7-y_hat)),
                             ifelse(
                             LTR.rating.categories=="aa",
                             log(logistic(t_9_x-y_hat)-logistic(t_8_x-y_hat)),
                             log(1-logistic(t_9_x-y_hat))
                           )
                           )
                           )
                           )
                           )
                           )
                           )
                           )
                           )
  
   -sum(log_likelihood)
}
start <- list(beta_1=1,beta_2=1,beta_3=1,beta_4=1,beta_5=1,beta_6=1,beta_7=1,beta_8=1,beta_9=1,beta_10=1,beta_11=1,beta_12=1,beta_13=1,beta_14=1,constant=1,t_2=1,t_3=1,t_4=1,t_5=1,t_6=1,t_7=1,t_8=1,t_9=1)
# f_2_fit <- stats4::mle(f_2,start = start,nobs = nrow(data))
tryCatch(
    {
      f_2_fit <- stats4::mle(f_2,start = start,nobs = nrow(data), method = "L-BFGS-B",lower = c(rep(-Inf,(ncol(data)-2)),rep(0,length(start)-(ncol(data)-2))),upper = rep(Inf,length(start)))
    }
    ,warning = function(war)
        {
            
        }
        ,error = function(err)
        {
          
        }
  
  )
while(!exists("f_2_fit")){
  for(i in 1:length(start)){
    if(i <= (ncol(data)-3)){
      start[[i]] <- runif(1,min = -1,max = 1)
    }else{
      start[[i]] <- runif(1,min = 0,max = 1) 
    }
  }
  tryCatch(
    {
      f_2_fit <- stats4::mle(f_2,start = start,nobs = nrow(data))
    }
    ,warning = function(war)
        {
            
        }
        ,error = function(err)
        {
          
        }
  
  )
}

start_2 <- start
coeff_2 <- f_2_fit@coef
```



```{r}
start <- list(beta_2=1,beta_3=1,beta_4=1,beta_5=1,beta_6=1,beta_7=1,beta_8=1,beta_9=1,beta_10=1,beta_11=1,beta_12=1,beta_13=1,beta_14=1,t_1=1,t_2=1,t_3=1,t_4=1,t_5=1,t_6=1,t_7=1,t_8=1,t_9=1)
# f_3_fit <- stats4::mle(f_1,start = start,fixed = list(beta_1=1),nobs = nrow(data))
tryCatch(
    {
      f_3_fit <- stats4::mle(f_1,start = start,fixed = list(beta_1=1),nobs = nrow(data), method = "L-BFGS-B",lower = c(rep(-Inf,(ncol(data)-2)),rep(0,length(start)-(ncol(data)-2))),upper = rep(Inf,length(start)))
    }
    ,warning = function(war)
        {
            
        }
        ,error = function(err)
        {
          
        }
  
  )
while(!exists("f_3_fit")){
  for(i in 1:length(start)){
    if(i <= (ncol(data)-3-1)){
      start[[i]] <- runif(1,min = -1,max = 1)
    }else{
      start[[i]] <- runif(1,min = 0,max = 1) 
    }
  }
  tryCatch(
    {
      f_3_fit <- stats4::mle(f_1,start = start,fixed = list(beta_1=1),nobs = nrow(data), method = "L-BFGS-B",lower = c(rep(-Inf,(ncol(data)-2)),rep(0,length(start)-(ncol(data)-2))),upper = rep(Inf,length(start)))
    }
    ,warning = function(war)
        {
            
        }
        ,error = function(err)
        {
          
        }
  
  )
}

start_3 <- start
coeff_3 <- f_3_fit@coef
detach(data)
save(list = c("start_1","start_2","start_3","f_1_fit","f_2_fit","f_3_fit"),file = "model.RData")
```









