---
title: "OLR"
author: '610811101'
date: "2020/10/6"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
library(oglmx) # oglmx
library(magrittr)
```



```{r}
setwd("G:/我的雲端硬碟/統計專論/作業一")
data <- read.csv("G:/我的雲端硬碟/統計專論/作業一/data_1.csv")
categories_levels <- c("d","c","cc","ccc","b","bb","bbb","a","aa","aaa")
data$LTR.rating.categories <- factor(data$LTR.rating.categories,levels = categories_levels)

print("LTR.rating.categories的分布狀況")
summary(data$LTR.rating.categories)
data <- data[!(is.na(data) %>% rowSums()),] 
# is.na(data) %>% colSums()
# data$constant <- 1
print("去除了缺失值後，LTR.rating.categories的分布狀況")
summary(data$LTR.rating.categories)

print("25,50,75分位數  ")
qua <- quantile(as.numeric(data$LTR.rating.categories),1:3/4,na.rm = T)
categories_levels[qua] %>% `names<-`(names(qua))
```


# model 

這邊使用了一個package "oglmx"，他可以固定係數或是是否保留截距項。  
但是保留的參數，在model的summary看不到，要去看allparams才有。   


```{r}
olm_c <- oglmx(LTR.rating.categories~ IC + OM + TDL + DP + MBA + RDA + REA + CEA + CBA + TA + beta + sigma + size +  S.P.500.return,data = data, delta=0,threshparam = c(0,rep(NA,7)),link =  "logit")

olm_nc <- oglmx(LTR.rating.categories~ IC + OM + TDL + DP + MBA + RDA + REA + CEA + CBA + TA + beta + sigma + size +  S.P.500.return,data = data, constantMEAN=F, constantSD= F, delta=0,link =  "logit")

olm_coef1Setting1 <- oglmx(LTR.rating.categories~ IC + OM + TDL + DP + MBA + RDA + REA + CEA + CBA + TA + beta + sigma + size +  S.P.500.return,data = data, constantMEAN=F, constantSD= T,delta=0, beta = c(1,rep(NA,13)),link =  "logit")


```




# 沒有截距項的ordered logistic regression  


```{r}
summary(olm_c)
olm_c$allparams
```


# 有截距項的ordered logistic regression  


```{r}
summary(olm_nc)
olm_nc$allparams
```


# 首項係數為1的ordered logistic regression  




```{r}
summary(olm_coef1Setting1)
olm_coef1Setting1$allparams
```



