---
title: "R-Package"
author: '610811101'
date: "2020/8/5"
output:
  html_document:
    code_folding: hide
    df_print: paged
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
---

```{r include=FALSE}
library(tidyverse)
library(jiebaR)
library(highcharter)
library(tidytext)
library(quanteda)
library("Rtsne")
library(magrittr)
library(wordcloud)
library(word2vec)
library(proxy)
data_package <- tools::CRAN_package_db() %>%
  select(Package,Title,Description,Imports,Author)
# data_package <- data_package %>%
#   select(Package,Title,Description,Imports)

# is_RStudio <- ifelse(grepl("RStudio",data_package$Author),"RStudio","others")
Rstudio_pg <- c("tidyverse","ggplot2","dplyr","tidyr","purrr","stringr","shiny","rmarkdown","flexdashboard","tensorflow","tidymodels","sparklyr","plumber","reticulate")


# is_RStudio <- ifelse(grepl("RStudio",package_Imports$Author),ifelse(package_Imports$Package %in% Rstudio_pg,"best","RStudio"),"others")
load("G:\\我的雲端硬碟\\meeting\\Task_Views.RData")
data_package <- left_join(data_package,Task_Views,by = "Package")
data_package$Topics[is.na(data_package$Topics)] <- "others"
```



# word cloud

```{r fig.height=10, fig.width=10}
print("Imports")
data_package %>%   
  unnest_tokens(word,Imports) %>%
  filter(grepl("[A-Za-z]+",word)) %>%
  count(word,sort = T) %$%
  # bind_tf_idf(word,Package,n) %>%
  # filter(idf>1) %$%
  wordcloud(words = word,freq = n,max.words = 20)
```


```{r fig.height=10, fig.width=10}
print("Description")
data_package %>%   
  unnest_tokens(word,Description) %>%
  filter(grepl("[A-Za-z]+",word)) %>%
  count(Package,word) %>%
  bind_tf_idf(word,Package,n) %>%
  filter(tf_idf>0.5) %>%
  select(-n) %>%
  count(word,sort = T) %$%
  wordcloud(words = word,freq = n,max.words = 20)
```


```{r fig.height=10, fig.width=10}
print("Title")
data_package %>% 
  mutate(text= paste(Package,Title)) %>%   
  unnest_tokens(word,text) %>%
  filter(grepl("[A-Za-z]+",word)) %>%
  count(Package,word) %>%
  bind_tf_idf(word,Package,n) %>%
  filter(tf_idf>0.5) %>%
  select(-n) %>%
  count(word,sort = T) %$%
  wordcloud(words = word,freq = n,max.words = 20)
```



# mds,t-sne,umap  by tf_idf


## Description  

```{r}
wordvec_model <- word2vec(x = data_package$Description,dim = 50)


package_Description <- data_package %>%   
  unnest_tokens(word,Description) %>%
  filter(grepl("[A-Za-z]+",word)) %>%
  count(Package,word,sort = T) %>%
  bind_tf_idf(word,Package,n) %>%
  filter(tf_idf>0.5)

package_Description <- package_Description$word %>% 
  as.vector() %>% 
  unique() %>%
  predict(wordvec_model,newdata = . , type = "embedding") %>%
  as.data.frame() %>%
  mutate(word = row.names(.)) %>%
  left_join(x = package_Description,y = ., by = "word")


package_Description <- package_Description %>% 
  group_by(Package) %>% 
  summarise_at(paste0("V",1:50),mean,na.rm = T) %>%
  as.data.frame() %>%
  `row.names<-`(.$Package) %>%
  .[,-1] 



package_Description <- package_Description[!is.na(package_Description[,1]),]
```

```{r}
t <- Sys.time()

package_Description_MDS_Euclidean <- package_Description %>%
  dist() %>% 
  cmdscale() %>%
  as.data.frame() %>%
  mutate(Package = row.names(.))

names(package_Description_MDS_Euclidean) <- c("x","y","Package")
package_Description_MDS_Euclidean <- left_join(package_Description_MDS_Euclidean,data_package,by = "Package")

is_RStudio <- ifelse(grepl("RStudio",package_Description_MDS_Euclidean$Author),ifelse(package_Description_MDS_Euclidean$Package %in% Rstudio_pg,"best","RStudio"),"others")

print("MDS use times")
Sys.time()-t
rm(t)
```

```{r}
t <- Sys.time()

hchart(package_Description_MDS_Euclidean,"scatter", hcaes(x=x,y=y,group = is_RStudio,label = Package ,value = Description)) %>%
  hc_title(text ="Description") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))

print("plot use times")
Sys.time()-t
rm(t)
```

```{r fig.height=15}
t <- Sys.time()

hchart(package_Description_MDS_Euclidean,"scatter", hcaes(x=x,y=y,group = Topics,label = Package ,value = Description)) %>%
  hc_title(text ="Description") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))


print("plot use times")
Sys.time()-t
rm(t)
```

```{r}
t <- Sys.time()

package_Description_uni <- package_Description %>%
    as.matrix() %>%
    unique()


package_Description_tsne <-  package_Description_uni %>%
  Rtsne() %$%
  Y %>% 
  as.data.frame() %>% 
  mutate(Package = row.names(package_Description_uni))






names(package_Description_tsne) <- c("x","y","Package")
package_Description_tsne <- left_join(package_Description_tsne,data_package,by = "Package")

is_RStudio <- ifelse(grepl("RStudio",package_Description_tsne$Author),ifelse(package_Description_tsne$Package %in% Rstudio_pg,"best","RStudio"),"others")

print("T-SNE use times")
Sys.time()-t
rm(t)
```

```{r}
t <- Sys.time()

hchart(package_Description_tsne,"scatter", hcaes(x=x,y=y,group = is_RStudio,label = Package ,value = Description)) %>%
  hc_title(text ="Description") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))

print("plot use times")
Sys.time()-t
rm(t)
```

```{r fig.height=15}
t <- Sys.time()

hchart(package_Description_tsne,"scatter", hcaes(x=x,y=y,group = Topics,label = Package ,value = Description)) %>%
  hc_title(text ="Description") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))

print("plot use times")
Sys.time()-t
rm(t)
```

```{r}
t <- Sys.time()

package_Description_umap_model <- umap::umap(package_Description)
package_Description_umap <- 
  package_Description_umap_model$layout%>% 
  as.data.frame() %>% 
  mutate(Package = row.names(package_Description))

names(package_Description_umap) <- c("x","y","Package")
package_Description_umap <- left_join(package_Description_umap,data_package,by = "Package")

is_RStudio <- ifelse(grepl("RStudio",package_Description_umap$Author),ifelse(package_Description_umap$Package %in% Rstudio_pg,"best","RStudio"),"others")

print("UMAP use times")
Sys.time()-t
rm(t)
```

```{r}
t <- Sys.time()

hchart(package_Description_umap,"scatter", hcaes(x=x,y=y,group = is_RStudio,label = Package ,value = Description)) %>%
  hc_title(text ="Description") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))

print("plot use times")
Sys.time()-t
rm(t)
```

```{r fig.height=15}
t <- Sys.time()

hchart(package_Description_umap,"scatter", hcaes(x=x,y=y,group = Topics,label = Package ,value = Description)) %>%
  hc_title(text ="Description") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))

print("plot use times")
Sys.time()-t
rm(t)
```

## Title  


```{r}
wordvec_model <- word2vec(x = data_package$Title,dim = 50)


package_Title <- data_package %>%   
  unnest_tokens(word,Title) %>%
  filter(grepl("[A-Za-z]+",word)) %>%
  count(Package,word,sort = T) %>%
  bind_tf_idf(word,Package,n) %>%
  filter(tf_idf>0.5)

package_Title <- package_Title$word %>% 
  as.vector() %>% 
  unique() %>%
  predict(wordvec_model,newdata = . , type = "embedding") %>%
  as.data.frame() %>%
  mutate(word = row.names(.)) %>%
  left_join(x = package_Title,y = ., by = "word")


package_Title <- package_Title %>% 
  group_by(Package) %>% 
  summarise_at(paste0("V",1:50),mean,na.rm = T) %>%
  as.data.frame() %>%
  `row.names<-`(.$Package) %>%
  .[,-1] 



package_Title <- package_Title[!is.na(package_Title[,1]),]
```

```{r}
t <- Sys.time()

package_Title_MDS_Euclidean <- package_Title %>%
  dist() %>% 
  cmdscale() %>%
  as.data.frame() %>%
  mutate(Package = row.names(.))

names(package_Title_MDS_Euclidean) <- c("x","y","Package")
package_Title_MDS_Euclidean <- left_join(package_Title_MDS_Euclidean,data_package,by = "Package")

is_RStudio <- ifelse(grepl("RStudio",package_Title_MDS_Euclidean$Author),ifelse(package_Title_MDS_Euclidean$Package %in% Rstudio_pg,"best","RStudio"),"others")

print("MDS use times")
Sys.time()-t
rm(t)
```

```{r}
t <- Sys.time()

hchart(package_Title_MDS_Euclidean,"scatter", hcaes(x=x,y=y,group = is_RStudio,label = Package ,value = Description)) %>%
  hc_title(text ="Title") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))

print("plot use times")
Sys.time()-t
rm(t)
```

```{r fig.height=15}
t <- Sys.time()

hchart(package_Title_MDS_Euclidean,"scatter", hcaes(x=x,y=y,group = Topics,label = Package ,value = Description)) %>%
  hc_title(text ="Title") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))


print("plot use times")
Sys.time()-t
rm(t)
```

```{r}
t <- Sys.time()

package_Title_uni <- package_Title %>%
    as.matrix() %>%
    unique()


package_Title_tsne <-  package_Title_uni %>%
  Rtsne() %$%
  Y %>% 
  as.data.frame() %>% 
  mutate(Package = row.names(package_Title_uni))






names(package_Title_tsne) <- c("x","y","Package")
package_Title_tsne <- left_join(package_Title_tsne,data_package,by = "Package")

is_RStudio <- ifelse(grepl("RStudio",package_Title_tsne$Author),ifelse(package_Title_tsne$Package %in% Rstudio_pg,"best","RStudio"),"others")

print("T-SNE use times")
Sys.time()-t
rm(t)
```

```{r}
t <- Sys.time()

hchart(package_Title_tsne,"scatter", hcaes(x=x,y=y,group = is_RStudio,label = Package ,value = Description)) %>%
  hc_title(text ="Title") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))

print("plot use times")
Sys.time()-t
rm(t)
```

```{r fig.height=15}
t <- Sys.time()

hchart(package_Title_tsne,"scatter", hcaes(x=x,y=y,group = Topics,label = Package ,value = Description)) %>%
  hc_title(text ="Title") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))

print("plot use times")
Sys.time()-t
rm(t)
```

```{r}
t <- Sys.time()

package_Title_umap_model <- umap::umap(package_Title)
package_Title_umap <- 
  package_Title_umap_model$layout%>% 
  as.data.frame() %>% 
  mutate(Package = row.names(package_Title))

names(package_Title_umap) <- c("x","y","Package")
package_Title_umap <- left_join(package_Title_umap,data_package,by = "Package")

is_RStudio <- ifelse(grepl("RStudio",package_Title_umap$Author),ifelse(package_Title_umap$Package %in% Rstudio_pg,"best","RStudio"),"others")

print("UMAP use times")
Sys.time()-t
rm(t)
```

```{r}
t <- Sys.time()

hchart(package_Title_umap,"scatter", hcaes(x=x,y=y,group = is_RStudio,label = Package ,value = Description)) %>%
  hc_title(text ="Title") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))

print("plot use times")
Sys.time()-t
rm(t)
```

```{r fig.height=15}
t <- Sys.time()

hchart(package_Title_umap,"scatter", hcaes(x=x,y=y,group = Topics,label = Package ,value = Description)) %>%
  hc_title(text ="Title") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))

print("plot use times")
Sys.time()-t
rm(t)
```

# mds,t-sne,umap by stop_words  

## Description  

```{r}
wordvec_model_50 <- word2vec(x = data_package$Description,dim = 50)


package_Description <- data_package %>%   
  unnest_tokens(word,Description) %>%
  filter(grepl("[A-Za-z]+",word)) %>%
  count(Package,word,sort = T) %>%
  bind_tf_idf(word,Package,n) %>%
  anti_join(stop_words, by = c("word" = "word"))

package_Description <- package_Description$word %>% 
  as.vector() %>% 
  unique() %>%
  predict(wordvec_model_50,newdata = . , type = "embedding") %>%
  as.data.frame() %>%
  mutate(word = row.names(.)) %>%
  left_join(x = package_Description,y = ., by = "word")


package_Description <- package_Description %>% 
  group_by(Package) %>% 
  summarise_at(paste0("V",1:50),mean,na.rm = T) %>%
  as.data.frame() %>%
  `row.names<-`(.$Package) %>%
  .[,-1] 



package_Description <- package_Description[!is.na(package_Description[,1]),]

```


```{r}
t <- Sys.time()

package_Description_MDS_Euclidean <- package_Description %>%
  dist() %>% 
  cmdscale() %>%
  as.data.frame() %>%
  mutate(Package = row.names(.))

names(package_Description_MDS_Euclidean) <- c("x","y","Package")
package_Description_MDS_Euclidean <- left_join(package_Description_MDS_Euclidean,data_package,by = "Package")

is_RStudio <- ifelse(grepl("RStudio",package_Description_MDS_Euclidean$Author),ifelse(package_Description_MDS_Euclidean$Package %in% Rstudio_pg,"best","RStudio"),"others")

print("MDS use times")
Sys.time()-t
rm(t)
```

```{r}
t <- Sys.time()

hchart(package_Description_MDS_Euclidean,"scatter", hcaes(x=x,y=y,group = is_RStudio,label = Package ,value = Description)) %>%
  hc_title(text ="Description") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))

print("plot use times")
Sys.time()-t
rm(t)
```

```{r fig.height=15}
t <- Sys.time()

hchart(package_Description_MDS_Euclidean,"scatter", hcaes(x=x,y=y,group = Topics,label = Package ,value = Description)) %>%
  hc_title(text ="Description") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))


print("plot use times")
Sys.time()-t
rm(t)
```

```{r}
t <- Sys.time()

package_Description_uni <- package_Description %>%
    as.matrix() %>%
    unique()


package_Description_tsne <-  package_Description_uni %>%
  Rtsne() %$%
  Y %>% 
  as.data.frame() %>% 
  mutate(Package = row.names(package_Description_uni))






names(package_Description_tsne) <- c("x","y","Package")
package_Description_tsne <- left_join(package_Description_tsne,data_package,by = "Package")

is_RStudio <- ifelse(grepl("RStudio",package_Description_tsne$Author),ifelse(package_Description_tsne$Package %in% Rstudio_pg,"best","RStudio"),"others")

print("T-SNE use times")
Sys.time()-t
rm(t)
```

```{r}
t <- Sys.time()

hchart(package_Description_tsne,"scatter", hcaes(x=x,y=y,group = is_RStudio,label = Package ,value = Description)) %>%
  hc_title(text ="Description") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))

print("plot use times")
Sys.time()-t
rm(t)
```

```{r fig.height=15}
t <- Sys.time()

hchart(package_Description_tsne,"scatter", hcaes(x=x,y=y,group = Topics,label = Package ,value = Description)) %>%
  hc_title(text ="Description") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))

print("plot use times")
Sys.time()-t
rm(t)
```

```{r}
t <- Sys.time()

package_Description_umap_model <- umap::umap(package_Description)
package_Description_umap <- 
  package_Description_umap_model$layout%>% 
  as.data.frame() %>% 
  mutate(Package = row.names(package_Description))

names(package_Description_umap) <- c("x","y","Package")
package_Description_umap <- left_join(package_Description_umap,data_package,by = "Package")

is_RStudio <- ifelse(grepl("RStudio",package_Description_umap$Author),ifelse(package_Description_umap$Package %in% Rstudio_pg,"best","RStudio"),"others")

print("UMAP use times")
Sys.time()-t
rm(t)
```

```{r}
t <- Sys.time()

hchart(package_Description_umap,"scatter", hcaes(x=x,y=y,group = is_RStudio,label = Package ,value = Description)) %>%
  hc_title(text ="Description") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))

print("plot use times")
Sys.time()-t
rm(t)
```

```{r fig.height=15}
t <- Sys.time()

hchart(package_Description_umap,"scatter", hcaes(x=x,y=y,group = Topics,label = Package ,value = Description)) %>%
  hc_title(text ="Description") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))

print("plot use times")
Sys.time()-t
rm(t)
```

## Title    

```{r}
wordvec_model <- word2vec(x = data_package$Title,dim = 50)


package_Title <- data_package %>%   
  unnest_tokens(word,Title) %>%
  filter(grepl("[A-Za-z]+",word)) %>%
  count(Package,word,sort = T) %>%
  bind_tf_idf(word,Package,n) %>%
  anti_join(stop_words, by = c("word" = "word"))

package_Title <- package_Title$word %>% 
  as.vector() %>% 
  unique() %>%
  predict(wordvec_model,newdata = . , type = "embedding") %>%
  as.data.frame() %>%
  mutate(word = row.names(.)) %>%
  left_join(x = package_Title,y = ., by = "word")


package_Title <- package_Title %>% 
  group_by(Package) %>% 
  summarise_at(paste0("V",1:50),mean,na.rm = T) %>%
  as.data.frame() %>%
  `row.names<-`(.$Package) %>%
  .[,-1] 



package_Title <- package_Title[!is.na(package_Title[,1]),]
```


```{r}
t <- Sys.time()

package_Title_MDS_Euclidean <- package_Title %>%
  dist() %>% 
  cmdscale() %>%
  as.data.frame() %>%
  mutate(Package = row.names(.))

names(package_Title_MDS_Euclidean) <- c("x","y","Package")
package_Title_MDS_Euclidean <- left_join(package_Title_MDS_Euclidean,data_package,by = "Package")

is_RStudio <- ifelse(grepl("RStudio",package_Title_MDS_Euclidean$Author),ifelse(package_Title_MDS_Euclidean$Package %in% Rstudio_pg,"best","RStudio"),"others")

print("MDS use times")
Sys.time()-t
rm(t)
```

```{r}
t <- Sys.time()

hchart(package_Title_MDS_Euclidean,"scatter", hcaes(x=x,y=y,group = is_RStudio,label = Package ,value = Description)) %>%
  hc_title(text ="Title") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))

print("plot use times")
Sys.time()-t
rm(t)
```

```{r fig.height=15}
t <- Sys.time()

hchart(package_Title_MDS_Euclidean,"scatter", hcaes(x=x,y=y,group = Topics,label = Package ,value = Description)) %>%
  hc_title(text ="Title") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))


print("plot use times")
Sys.time()-t
rm(t)
```

```{r}
t <- Sys.time()

package_Title_uni <- package_Title %>%
    as.matrix() %>%
    unique()


package_Title_tsne <-  package_Title_uni %>%
  Rtsne() %$%
  Y %>% 
  as.data.frame() %>% 
  mutate(Package = row.names(package_Title_uni))






names(package_Title_tsne) <- c("x","y","Package")
package_Title_tsne <- left_join(package_Title_tsne,data_package,by = "Package")

is_RStudio <- ifelse(grepl("RStudio",package_Title_tsne$Author),ifelse(package_Title_tsne$Package %in% Rstudio_pg,"best","RStudio"),"others")

print("T-SNE use times")
Sys.time()-t
rm(t)
```

```{r}
t <- Sys.time()

hchart(package_Title_tsne,"scatter", hcaes(x=x,y=y,group = is_RStudio,label = Package ,value = Description)) %>%
  hc_title(text ="Title") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))

print("plot use times")
Sys.time()-t
rm(t)
```

```{r fig.height=15}
t <- Sys.time()

hchart(package_Title_tsne,"scatter", hcaes(x=x,y=y,group = Topics,label = Package ,value = Description)) %>%
  hc_title(text ="Title") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))

print("plot use times")
Sys.time()-t
rm(t)
```

```{r}
t <- Sys.time()

package_Title_umap_model <- umap::umap(package_Title)
package_Title_umap <- 
  package_Title_umap_model$layout%>% 
  as.data.frame() %>% 
  mutate(Package = row.names(package_Title))

names(package_Title_umap) <- c("x","y","Package")
package_Title_umap <- left_join(package_Title_umap,data_package,by = "Package")

is_RStudio <- ifelse(grepl("RStudio",package_Title_umap$Author),ifelse(package_Title_umap$Package %in% Rstudio_pg,"best","RStudio"),"others")

print("UMAP use times")
Sys.time()-t
rm(t)
```

```{r}
t <- Sys.time()

hchart(package_Title_umap,"scatter", hcaes(x=x,y=y,group = is_RStudio,label = Package ,value = Description)) %>%
  hc_title(text ="Title") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))

print("plot use times")
Sys.time()-t
rm(t)
```

```{r fig.height=15}
t <- Sys.time()

hchart(package_Title_umap,"scatter", hcaes(x=x,y=y,group = Topics,label = Package ,value = Description)) %>%
  hc_title(text ="Title") %>%
  hc_chart(zoomType ="xy") %>%
  hc_tooltip(formatter = JS("function () {
                                   return '<b>' + this.point.label + '</b><br/>'+'Description: '+this.point.value;}"))

print("plot use times")
Sys.time()-t
rm(t)
```
