---
title: "T-SNE-predict"
author: '610811101'
date: "2020/11/20"
output:
  html_document:
    code_folding: hide
    df_print: paged
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
---


 
 

```{r include=FALSE}
library(highcharter)
library(tidyverse)
library(tidytext)
library(Rtsne)
library(magrittr)
```




```{r}
finaldata9815 <- read.csv("G:/我的雲端硬碟/meeting/finaldata9815.csv")

colname <- c("IC","OM","TDL","DP","MBA","RDA","REA","CEA","CBA","TA","beta","sigma","size","S.P.500.return")
finaldata9815 <- finaldata9815[,c(colname,"LTR.rating.categories")]
finaldata9815 <- finaldata9815[!(is.na(finaldata9815) %>% rowSums()),]

data_out <- read.csv("G:/我的雲端硬碟/meeting/data_out.csv")
data_in <- read.csv("G:/我的雲端硬碟/meeting/data_in.csv")

mnist <- snedata::download_mnist()

```






# function  


```{r}
center <- function(x){
  x_mean <- matrix(colMeans(x),nrow = nrow(x),ncol = ncol(x),byrow = T)
  x-x_mean
}

train_tsne <- function(data){
  ## the function is use by myself , so it has not check anything
  pca <- prcomp(data)
  Y_init <- as.matrix(pca$x[,1:2])
  
  tsne <- Rtsne(data,check_duplicates = F,Y_init = Y_init)
  tsne[["Y_init"]] <- Y_init
  tsne[["pca_coef"]] <- as.matrix(pca$rotation[,1:2])
  tsne[["center"]] <- pca$center
  class(tsne) <- "TSNE"
  tsne
}

# predict_tsne <- function(TSNE,train,test){
#   ## the function is use by myself , so it has not check anything 
#   train_pca <- prcomp(train)
#   test_mean <- matrix(colMeans(train),nrow = nrow(test),ncol = ncol(train))
#   train_pca_value <- as.matrix(train_pca$x[,1:2])
#   test_pca_value <- as.matrix(test-test_mean) %*% as.matrix(train_pca$rotation[,1:2])
#   test_predict <- matrix(nrow = nrow(test),ncol = 2) %>%
#     as.data.frame() %>%
#     `names<-`(c("x","y"))
#   for(i in 1:nrow(test)){
#     
#   }
# }

predict_tsne <- function(TSNE,test,k = 5){
  ## the function is use by myself , so it has not check anything 
  if(class(TSNE)!="TSNE"){
    stop("class is not TSNE")
  }
  test_mean <- matrix(TSNE$center,nrow = nrow(test),ncol = ncol(test),byrow = T)
  
  RS <- TSNE$Y-TSNE$Y_init
  
  test_pca_value <- as.matrix(test-test_mean) %*% TSNE$pca_coef
  
  test_predict <- matrix(nrow = nrow(test),ncol = 2) %>%
    as.data.frame() %>%
    `names<-`(c("x","y"))
  
  for(i in 1:nrow(test)){
    test_dist_order <- (TSNE$Y_init-matrix(test_pca_value[i,],ncol = 2,nrow = nrow(TSNE$Y_init),byrow = T))^2 %>% rowSums() %>% order()
    index <- test_dist_order[1:k]
    move <- RS[index,] %>% colMeans()
    test_predict[i,] <- test_pca_value[i,]+move
  }
  test_predict
}


all_tsne <- function(TSNE,data){
  ## the function is use by myself , so it has not check anything 
  if(class(TSNE)!="TSNE"){
    stop("class is not TSNE")
  }
  data_mean <- matrix(TSNE$center,nrow = nrow(data),ncol = ncol(data),byrow = T)
  
  data_pca_value <- as.matrix(data-data_mean) %*% TSNE$pca_coef
  tsne <- Rtsne(data,check_duplicates = F,Y_init = data_pca_value)
  
  tsne
}
```







# iris  


```{r}
set.seed(610811101)
iris_index <- sample(1:nrow(iris),size = floor(0.8*nrow(iris)))
iris_train <- iris[iris_index,]
iris_test <- iris[-iris_index,]
set.seed(610811101)
iris_tsne <- train_tsne(iris_train[,1:4])
iris_pred <- predict_tsne(TSNE = iris_tsne,test = iris_test[,1:4],k = 3) %>%
  as.data.frame() %>%
  cbind(iris_test$Species) %>%
  `names<-`(c("x","y","Species"))


```




```{r}
iris_tsne %$%
  Y %>%
  as.data.frame() %>%
  cbind(iris_train$Species) %>%
  `names<-`(c("x","y","Species")) %>%
  hchart("scatter", hcaes(x=x,y=y,group = Species)) %>%
  hc_title(text ="iris_train") 


```






## 使用MDS predict

```{r}
  
hchart(iris_pred,"scatter", hcaes(x=x,y=y,group = Species)) %>%
  hc_title(text ="iris_pred") 
```

```{r}
  
iris_tsne %$%
  Y %>%
  as.data.frame() %>%
  cbind(iris_train$Species) %>%
  `names<-`(c("x","y","Species")) %>%
  rbind(iris_pred) %>%
  hchart("scatter", hcaes(x=x,y=y,group = Species)) %>%
  hc_title(text ="iris_all") 

```

## 用Multivariate multiple regression predict  

```{r}
iris_lm <- iris_tsne %$%
  Y %>%
  as.data.frame() %>%
  `names<-`(c("x","y"))  %>%
  cbind(iris_train[,1:4]) %>%
  lm(cbind(x,y)~.,data = .)    
    
iris_pred_2 <- predict(iris_lm,iris_test[,1:4]) %>%
  as.data.frame() %>%
  cbind(iris_test$Species) %>%
  `names<-`(c("x","y","Species")) 

  hchart(iris_pred_2,"scatter", hcaes(x=x,y=y,group = Species)) %>%
  hc_title(text ="iris_pred")
```


```{r}

iris_tsne %$%
  Y %>%
  as.data.frame() %>%
  cbind(iris_train$Species) %>%
  `names<-`(c("x","y","Species")) %>%
  rbind(iris_pred_2) %>%
  hchart("scatter", hcaes(x=x,y=y,group = Species)) %>%
  hc_title(text ="iris_all") 
```



## test data contrast  

```{r}
iris_all <- all_tsne(iris_tsne,data = iris[,1:4])

iris_cont <- iris_all$Y[-iris_index,] %>%
  as.data.frame() %>%
  cbind(group = "t-sne") %>%
  `names<-`(c("x","y","group")) %>%
  rbind(cbind(iris_pred[,1:2],group = "t-sne-pred"))  %>%
  rbind(cbind(iris_pred_2[,1:2],group = "t-sne-pred2"))

hchart(iris_cont,"scatter", hcaes(x=x,y=y,group = group)) %>%
  hc_title(text ="iris_pred")
  
```



# mnist   


```{r}
set.seed(610811101)
mnist_index <- sample(1:nrow(mnist),size = floor(0.8*nrow(mnist)))
mnist_train <- mnist[mnist_index,]
mnist_test <- mnist[-mnist_index,]
set.seed(610811101)
mnist_tsne <- train_tsne(mnist_train[,1:784])
mnist_pred <- predict_tsne(TSNE = mnist_tsne,test = mnist_test[,1:784])%>%
  as.data.frame() %>%
  cbind(mnist_test$Label) %>%
  `names<-`(c("x","y","Label"))


```



```{r}



mnist_tsne %$%
  Y %>%
  as.data.frame() %>%
  cbind(mnist_train$Label) %>%
  `names<-`(c("x","y","Label")) %>%
  hchart("scatter", hcaes(x=x,y=y,group = Label)) %>%
  hc_title(text ="mnist_train") 
  

```

## 使用MDS predict  

```{r}

hchart(mnist_pred,"scatter", hcaes(x=x,y=y,group = Label)) %>%
  hc_title(text ="mnist_pred") 


```

```{r}

mnist_tsne %$%
  Y %>%
  as.data.frame() %>%
  cbind(mnist_train$Label) %>%
  `names<-`(c("x","y","Label")) %>%
  rbind(mnist_pred) %>%
  hchart("scatter", hcaes(x=x,y=y,group = Label)) %>%
  hc_title(text ="mnist_all") 

```

## 用Multivariate multiple regression predict  


```{r}
mnist_lm <- mnist_tsne %$%
  Y %>%
  as.data.frame() %>%
  `names<-`(c("x","y"))  %>%
  cbind(mnist_train[,1:784]) %>%
  lm(cbind(x,y)~.,data = .)    
    
mnist_pred_2 <- predict(mnist_lm,mnist_test[,1:784]) %>%
  as.data.frame() %>%
  cbind(mnist_test$Label) %>%
  `names<-`(c("x","y","Label")) 

hchart(mnist_pred_2,"scatter", hcaes(x=x,y=y,group = Label)) %>%
  hc_title(text ="mnist_pred") 
```


```{r}
mnist_tsne %$%
  Y %>%
  as.data.frame() %>%
  cbind(mnist_train$Label) %>%
  `names<-`(c("x","y","Label")) %>%
  rbind(mnist_pred_2) %>%
  hchart("scatter", hcaes(x=x,y=y,group = Label)) %>%
  hc_title(text ="mnist_all") 
```

## test data contrast  

```{r}
mnist_all <- all_tsne(mnist_tsne,data = mnist[,1:784])

mnist_cont <- mnist_all$Y[-mnist_index,] %>%
  as.data.frame() %>%
  cbind(group = "t-sne") %>%
  `names<-`(c("x","y","group")) %>%
  rbind(cbind(mnist_pred[,1:2],group = "t-sne-pred"))  %>%
  rbind(cbind(mnist_pred_2[,1:2],group = "t-sne-pred2"))

hchart(mnist_cont,"scatter", hcaes(x=x,y=y,group = group)) %>%
  hc_title(text ="mnist_pred")
  
```



