---
title: "CPM"
author: '610811101'
date: "2020/12/4"
always_allow_html: true
output:
  ioslides_presentation: 
    widescreen: true
    df_print: tibble 
  slidy_presentation: default

---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
library(MASS)
library(caret)
library(magrittr)
library(highcharter)
library(tidyr)
library(tibble)
```


```{r}
setwd("G:/我的雲端硬碟/統計專論/CPM2")
data_in <- read.csv("data_in.csv")
data_out <- read.csv("data_out.csv")

```



```{r}
cpm <- function (formula, data, weights, start, ..., subset, na.action, 
          contrasts = NULL, Hess = FALSE, model = TRUE, method = c("logistic", 
                                                                   "probit", "loglog", "cloglog", "cauchit")) 
{
  m <- match.call(expand.dots = FALSE)
  method <- match.arg(method)
  if (is.matrix(eval.parent(m$data))) 
    m$data <- as.data.frame(data)
  m$start <- m$Hess <- m$method <- m$model <- m$... <- NULL
  m[[1L]] <- quote(stats::model.frame)
  m <- eval.parent(m)
  Terms <- attr(m, "terms")
  x <- model.matrix(Terms, m, contrasts)
  xint <- match("(Intercept)", colnames(x), nomatch = 0L)
  n <- nrow(x)
  pc <- ncol(x)
  cons <- attr(x, "contrasts")
  if (xint > 0L) {
    x <- x[, -xint, drop = FALSE]
    pc <- pc - 1L
  }
  else warning("an intercept is needed and assumed")
  wt <- model.weights(m)
  if (!length(wt)) 
    wt <- rep(1, n)
  offset <- model.offset(m)
  if (length(offset) <= 1L) 
    offset <- rep(0, n)
  y <- model.response(m)
  
  #####
  X <- cbind(Intercept = rep(1, n), x)
  coefs <- matrix(ncol = ncol(X))  %>% as.data.frame()
  for(i in 1:n){
    w <- if(y[i]==1) as.numeric(y >= 1) else as.numeric(y >  y[i])
    fit <- switch(method, logistic = glm.fit(X[-i,], w[-i], wt[-i], 
                                             family = binomial(), offset = offset[-i]), probit = glm.fit(X[-i,], 
                                                                                                     w[-i], wt[-i], family = binomial("probit"), offset = offset[-i]), 
                  loglog = glm.fit(X[-i,], w[-i], wt[-i], family = binomial("probit"), 
                                   offset = offset[-i]), cloglog = glm.fit(X[-i,], w[-i], wt[-i], 
                                                                       family = binomial("probit"), offset = offset[-i]), 
                  cauchit = glm.fit(X[-i,], w[-i], wt[-i], family = binomial("cauchit"), 
                                    offset = offset[-i]))
    
    coefs[i,] <- fit$coefficients
  }
  
  coefs_mean <- colMeans(coefs,na.rm = T)
  beta <- coefs_mean[-1L]
  names(beta) <- colnames(x)
  h_fun <- data.frame(y=seq(0,1,0.001),eta = NA)
  #####
  eta <- if (pc) 
    offset + drop(x %*% beta)
  else offset + rep(0, n)
  pfun <- switch(method, logistic = plogis, probit = pnorm, 
                 loglog = pgumbel, cloglog = pGumbel, cauchit = pcauchy)
  mle <-  function(zeta){
    if(i==1){
      p <- pfun(zeta-eta)
    }else{
      p <- pfun(h_fun$eta[i-1]+log(exp(zeta)+1)-eta)
    }
    -sum(w*p+(1-w)*(1-p))
  }
  for(i in 1:nrow(h_fun)){
    w <- if(h_fun$y[i]==1) as.numeric(y < 1) else as.numeric(y <=  h_fun$y[i])
    # w <- (y <= h_fun$y[i])
    res <- optim(0, mle, method="BFGS")
    if(i == 1){
      h_fun$eta[i] <- res$par
    }else{
      h_fun$eta[i] <- h_fun$eta[i-1]+log(exp(res$par)+1)
    }
  }
  
  

  fit <- list(coefs = coefs ,coefficients = beta, h_fun = h_fun, n = sum(wt), nobs = sum(wt), terms = Terms,
              call = match.call(), method = method,
              lp = eta)
  if (model) 
    fit$model <- m
  fit$na.action <- attr(m, "na.action")
  fit$contrasts <- cons
  fit$xlevels <- .getXlevels(Terms, m)
  fit
}

```


```{r}
predict.cpm <- function(object, newdata){
  eta <- drop(as.matrix(newdata) %*% object$coefficients)
  y <- rep(NA,length(eta))
  for(i in 1:length(eta)){
    test <- object$h_fun$eta>eta[i]
    if(any(test)){
      y[i] <- object$h_fun$y[ifelse(test[1],1,which(test)[1]-1)]
    }else{
      y[i] <- 1
    }
  }
  y
}
```

# logistic  


## coefficients


```{r}
test<-cpm(LGD~.-Instrument.ID-Date.of.Obligor.Default,data = data_in)

test$coefficients

```

## H function

```{r}
plot(test$h_fun$eta,test$h_fun$y,type = "l")
```







## confusionMatrix  


```{r}
y_hat_1 <- predict.cpm(test,data_in[,4:15])


LGD <- ifelse(data_in$LGD<1&data_in$LGD>0,"0-1",data_in$LGD)
y <- ifelse(y_hat_1<1&y_hat_1>0,"0-1",y_hat_1)
table(LGD,y,dnn = c("real","predict")) 

(data_in$LGD-y_hat_1)^2 %>% mean()
```

## confusionMatrix 



```{r}
y_hat_2 <- predict.cpm(test,data_out[,4:15])


LGD <- ifelse(data_out$LGD<1&data_out$LGD>0,"0-1",data_out$LGD)
y <- ifelse(y_hat_2<1&y_hat_2>0,"0-1",y_hat_2)
table(LGD,y,dnn = c("real","predict")) 

(data_out$LGD-y_hat_2)^2 %>% mean()
```


# probit  


## coefficients


```{r}
test<-cpm(LGD~.-Instrument.ID-Date.of.Obligor.Default,data = data_in,method = "probit")

test$coefficients

```

## H function

```{r}
plot(test$h_fun$eta,test$h_fun$y,type = "l")
```





## confusionMatrix  


```{r}
y_hat_3 <- predict.cpm(test,data_in[,4:15])


LGD <- ifelse(data_in$LGD<1&data_in$LGD>0,"0-1",data_in$LGD)
y <- ifelse(y_hat_3<1&y_hat_3>0,"0-1",y_hat_3)
table(LGD,y,dnn = c("real","predict")) 

(data_in$LGD-y_hat_3)^2 %>% mean()
```

## confusionMatrix 



```{r}
y_hat_4 <- predict.cpm(test,data_out[,4:15])


LGD <- ifelse(data_out$LGD<1&data_out$LGD>0,"0-1",data_out$LGD)
y <- ifelse(y_hat_4<1&y_hat_4>0,"0-1",y_hat_4)
table(LGD,y,dnn = c("real","predict")) 

(data_out$LGD-y_hat_4)^2 %>% mean()
```




## 比較   



```{r}
mean(abs(y_hat_1-y_hat_3))
```

```{r}
mean(abs(y_hat_2-y_hat_4))
```

